"""
    init for configs
"""
from .config import REQUIRED_FILE_FOR_ENGINE, DATA_PATH, ENGINE_PATH, SHOW_PROGRESS_BAR, REMOVE_STOP_WORDS
from .config import LOG_FILE, SHOW_DETAIL, RANKING_ALGO, TOTAL_N_RESULT, RANKING, SCORE_THRESHOLD, STOP_WORDS
